version: '3.4'

services:
  gameapidb:
    container_name: gameapidb
    environment:
       - POSTGRES_USER=admin
       - POSTGRES_PASSWORD=admin1234
       - POSTGRES_DB=GameapiDB
    restart: always
    ports:
       - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@aspnetrun.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports:
        - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin

  gamepromotion.api:
    container_name: gamepromotion.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=gameapidb;Port=5432;Database=GameapiDB;User Id=admin;Password=admin1234;"
    depends_on:
      - gameapidb
    ports:
      - "8000:80"